name:  🚀 Vite CI build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:

    runs-on: [self-hosted, Linux, X64]
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    strategy:
      matrix:
        node-version: [ 24 ]

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🟩 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 📥 Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: 🏗️ Build Vite Application
        run: pnpm run build
        env:
          VITE_EMAILJS_SERVICE_ID: ${{ secrets.VITE_EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}
          VITE_EMAILJS_PUBLIC_KEY: ${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}
          VITE_RSS2JSON_API_KEY: ${{ secrets.VITE_RSS2JSON_API_KEY }}
          VITE_RECAPTCHA_SITE_KEY: ${{ secrets.VITE_RECAPTCHA_SITE_KEY }}

      - name: 📂 Deploy
        run: |
          rsync -av ./dist/ /home/amiroff/htdocs/amiroff.org/

      - name: 🗑️ Purge Cloudflare Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
